### ISSUE TITLE
Deploy a Docker container registry system

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads-deployment#100]
We will need some place to store Docker images generated by the CI/CD scripts. This is likely going to be Project Quay.

**Comment by mcduffie** [comment]
Setting up using this guide: https://docs.projectquay.io/deploy_quay.html

**Comment by mcduffie** [comment]
For now need to disable SELinux but could turn back on using this guide:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_selinux/creating-selinux-policies-for-containers_using-selinux

**Comment by mcduffie** [comment]
Information on putting container runs into systemd files:
https://www.redhat.com/en/blog/floating-kwaaaay-podman-and-systemd

**Comment by mike-gangl** [comment]
@mcduffie do you envision Quay being a shared service across all Unity, or would be be per venue? pros and cons to each, but i think a shared service along side dockstore kind of makes sense.

**Comment by mcduffie** [comment]
I think it should be a shared service

**Comment by mcduffie** [comment]
- Successfully configured Quay to authenticate using Cognito
- Parameterized Quay coginito information into Terraform init.sh script
- Modified Terraform to create random passwords for postgresql and redis
- Exposed Quay to the world through a load balancer set up
- Still some timeouts when logging in that requires hitting back to resolve
- Issue with not being able to log in via Docker because of self signed certificates

**Comment by mcduffie** [comment]
* Modified Quay Terraform to use Amazon Linux 2 because of the instability of using RHEL8
* Fixed configuration default for storage location causing errors when trying to push to registry
* Successfully tested pushing local Docker image into deployed registry
  * Seems to require password used to access account not generated key

**Comment by mcduffie** [comment]
Todo
* Fix stall when using Cognito to log in
* Switch from internal Postgres to Amazon RDS based PostgreSQL
* Add S3 cloning of registry files
