### ISSUE TITLE
U-ADS API Documentation

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads-deployment#15]
Documentation on the APIs used for M2M communication. Points to third party documents with supplemental information.

### Acceptance Criteria
* Describes U-ADS APIs meant for external access
* Points to additional third party documentation
* Details Unity specific information
* Provides example usage
* Provides information on software libraries useful for access 

### Dependencies
* U-ADS Algorithm Catalog
* U-ADS Development Environment
* U-ADS CI/CD

**Comment by mcduffie** [comment]
Zenhub epic, no longer needed
