### ISSUE TITLE
Add health check endpoint for Jupyterhub

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads-deployment#157]
Create an SSM parameter following UCS provided naming convention /unity/healthCheck/<MARKETPLACE_ITEM>/<COMPONENT_NAME>/url and store  **juptyer/health** endpoint as the URL

SSM parameter name will be **/unity/healthCheck/ads/jupyterhub**

the SSM param should be automatically  created after a deployment of the service.

**Comment by GodwinShen** [comment]
@mcduffie any updates on this one?

**Comment by mcduffie** [comment]
Was going to implement when making HTTPD related changes, since that will change the URL.

**Comment by GodwinShen** [comment]
Blocked by https://github.com/unity-sds/unity-project-management/issues/170

**Comment by mcduffie** [comment]
Implemented
