### ISSUE TITLE
Add JWT Python package to app build Lambda function

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads-deployment#162]

**Comment by GodwinShen** [comment]
@edwinsarkissian , @mcduffie this one seems like a low hanging fruit, can I get a status update on this ticket?

**Comment by edwinsarkissian** [comment]
Hello Godwin,
It is done.
Edwin


From: GodwinShen ***@***.***>
Reply-To: unity-sds/unity-ads-deployment ***@***.***>
Date: Monday, May 13, 2024 at 6:10 PM
To: unity-sds/unity-ads-deployment ***@***.***>
Cc: "Sarkissian, Edwin (US 398E)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [unity-sds/unity-ads-deployment] Add JWT Python package to app build Lambda function (Issue #162)


@edwinsarkissian<https://urldefense.us/v3/__https:/github.com/edwinsarkissian__;!!PvBDto6Hs4WbVuu7!OXivBGttGn2oU8mCdSTeS5SU3m3H3YoeEVEkGAqAJDvxbzCBQQB6WHVZA0d63Tor-9goF0ME1xy7FnyQfgYsUEWFiZrjp39mWg$> , @mcduffie<https://urldefense.us/v3/__https:/github.com/mcduffie__;!!PvBDto6Hs4WbVuu7!OXivBGttGn2oU8mCdSTeS5SU3m3H3YoeEVEkGAqAJDvxbzCBQQB6WHVZA0d63Tor-9goF0ME1xy7FnyQfgYsUEWFiZoz1k3wMQ$> this one seems like a low hanging fruit, can I get a status update on this ticket?
