### ISSUE TITLE
App-package-gen and unity-app-gen must be pinned to releases not the main branch

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads-deployment#166]
https://github.com/unity-sds/unity-ads-deployment/blob/bc07f0d509a08823933bd212439ee962c8cc83b3/ci_cd/install_group_runner_x86_64_shell.tftpl#L187-L191

Anytime a new gitrunner is deployed (or if the instance crashes and a new one is brought up) it will fetch the lates code regardless of if it's been tested or not. By pinning this to a release or a specific commit hash, we  know what will be deployed regardless of _when_ the deployment happens.

**Comment by mike-gangl** [comment]
Any updates on this?

**Comment by mcduffie** [comment]
Use
-  app-pack-generator v0.4.0
- unity-app-generator v0.3.0

**Comment by mcduffie** [comment]
Preliminary support here:
https://github.com/unity-sds/unity-ads-deployment/commit/ac234e815d8ce2bbb5aa6bcc118114f5ecf31654

**Comment by edwinsarkissian** [comment]
This task is complete.  When the U-ADS "auto clone/build pipeline" is deployed, unity-app-gen and app-pack-gen are installed for the selected tags.  Currently, the defaults are 0.4.0 for app-pack-gen and 0.3.0 for unity-app-gen.

**Comment by mike-gangl** [comment]
@edwinsarkissian or @mcduffie  please close the ticket if you're done.
