### ISSUE TITLE
Permission error in APGS Built Applicaiton Pacakges

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads-deployment#176]
The error is caused by the umask set when jupyter-repo2docker is installed. I am not sure how I can enforce this as a package maintainer.

[Slack Message](https://jpl.slack.com/archives/G01EJJV7UH4/p1727219543633619?thread_ts=1727210435.482619&cid=G01EJJV7UH4)

The error is caused by the umask set when jupyter-repo2docker is installed. I am not sure how I can enforce this as a package maintainer.

The problem is /python3.12/site-packages/repo2docker/buildpacks/python3-login gets copies from where the python packages are written in your environment.

It carries with it those permission.

Inside of the docker image that is made it copies that file as root then the docker image is switched to the jovyan user. @Edwin Sarkissian the solution for you is to set the umask to something like 002 before installing the python packages. A quick fix is to set the umask and uninstall and install the jupyter-repo2docker image
Verify the permissions are readable by using this command:

```
ls -l $(find $(dirname $(which jupyter-repo2docker))/.. -name "python3-login")
```

**Comment by mcduffie** [comment]
Fixed by setting umask inside builder when deployed before installing Python packages.

**Comment by mcduffie** [comment]
Duplicated by #173
