### ISSUE TITLE
Review Dockstore Deployment Documentation

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads-deployment#26]
Review and edit Dockstore deployment documentation by going through steps independently

**Comment by mcduffie** [comment]
Confirm can deploy instance from documentation.

**Comment by mliukis** [comment]
Got all components deployed for the development.
Will work on registering a GitHub-based workflow next.

**Comment by mcduffie** [comment]
- Worked with Nick on dev deployment
- Had fully deployed
- When adding bogus workflow would not show up in search
- Nick looked at deployment
  - Significant amount of timeouts
  - Timeout occurred in registration process
  - Bucket for load balancer did not connect, fixed in deployment
- Masha will have to create a Github app under her account since they can not be passed to other users
- Updated documentation
- Possibly a good idea to create script to check deployment health
  - Various checks using AWS API and HTTP checks
  - Logs that give pieces of information to diagnose

**Comment by mcduffie** [comment]
Documentation updated.
Deployment using that document shown.
