### ISSUE TITLE
U-ADS Development Environment

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads-deployment#34]
The mechanisms and interfaces for a user to begin development work within the Unity System.

### Acceptance Criteria
* MCP deployed Jupyter Hub
* User can create a notebook in Jupyter Hub
* no VCS tie-ins required (?)
* Authentication (Work with U-CS) to see how 'simple' this is to set up- they had a version of this.
* Deployment diagram (e.g. what is needed for this to run, is it a per-tenant deployment, or shared across many tenants)
* Deployed in dev environment
* Deployed in 'test' environment for SounderSIPS users

**Comment by mcduffie** [comment]
Zenhub epic, no longer needed
