### ISSUE TITLE
U-ADS Continuous Integration/Continuous Delivery (CI/CD)

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads-deployment#35]
### Acceptance Criteria

* Creation of an algorithm package from code, configs, etc
* run automated tests agains packaged code
* publish Algorithm Package to the Algorithm Catalog
* Deployment diagram (e.g. what is needed for this to run, is it a per-tenant deployment, or shared across many tenants)
* Deployed to Dev environment
* Deployed to Test Environment

**Comment by mcduffie** [comment]
Zenhub epic, no longer needed
