### ISSUE TITLE
U-ADS Application Catalog

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads-deployment#4]
U-ADS infrastructure service component that stores and organizes metadata related to applications/algorithms that can be deployed for processing by U-SDS.

### Acceptance Criteria

* Deployed in MCP
* Accessible by MCP based Unity Components
* Ability to deploy a packaged algorithm to an algorithm catalog
* Ability to search an algorithm catalog by 'project' (e.g. SounderSIPS)
* Algorithm Catalog can contains link to CWL and Docker container
* Deployment diagram (e.g. what is needed for this to run, is it a per-tenant deployment, or shared across many tenants)

**Comment by mike-gangl** [comment]
@nlahaye and @mcduffie 

I'm glad we're moving forward with dockstore as it looks promising. In my opinion, the "deployment to MCP" and "SounderSIPS algorithm in Dockstore" are the biggest values gained. i'd push off the documentation and authentication portions of those tools for now- ideally getting something that SPS can deploy from dockstore would be a homerun.

Is there anything you need from me in getting this done? Any blockers i can help with?

**Comment by nlahaye** [comment]
@mike-gangl 

Thanks for offering to help! I have reached out to the Dockstore development team, as I found notes about a repo that contains their AWS deployment scripts. Unfortunately, they have said that they are unwilling to provide access to that repo, but they did offer to meet with us to provide recommendations about required AWS infrastructure. Access to their deployment scripts would be extremely helpful and reduce development/deployment time significantly, so any magic/convincing you could potentially do on that front would be very helpful. 

I can include you on the meeting invite once it is set?

**Comment by mcduffie** [comment]
Zenhub epic, no longer needed
