### ISSUE TITLE
As an algorithm developer, I'd like to easily identify an application package in the applicaton package catalog and deploy that algorithm into a running ADES so that the algorithm can be run. (Or, in the future, a workflow rather than a single algorithm)

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads-deployment#81]
Acceptance Criteria:

* Application Packages have a unique identifier (can be a string or a url or... something)
* Identifier can be referenced from programmatic access 
* Application package (which can be a single process or a task, or an entire workflow) can be deployed to an ADES endpoint

**Comment by mcduffie** [comment]
Closed, features moved into https://github.com/unity-sds/unity-project-management repo
