### ISSUE TITLE
As a SounderSIPS user, i want to build an application package automatically from within the Unity system

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads-deployment#82]
Acceptance Criteria:

* Unity users can build an applicaiton package
* Application package contains ...
  - metadata file outputs (for use in catalogging via U-DS)
  - Input/Output characterizations
  - WPS-T definition

**Comment by mcduffie** [comment]
Duplicate of [unity-project-management #67](https://github.com/unity-sds/unity-project-management/issues/67)
