### ISSUE TITLE
Convert Unity.py Application Package API to use Hosted Workflows

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads-deployment#87]
Currently the Unity.py access to Dockstore API uses deprecated end points. Convert to use Dockstore Hosted Workflows.

- [These series of tests](https://github.com/dockstore/dockstore/blob/develop/dockstore-integration-testing/src/test/java/io/dockstore/client/cli/HostedWorkflowIT.java) may be useful to see how to use hosted workflows in an automated way. 
- [Example of editing files using the API](https://github.com/dockstore/dockstore-ui2/blob/a5e2d99483dcc1522fdc22e44a26cea8bb0b908d/src/app/workflow/workflow-file-editor/workflow-file-editor.component.ts#L111)
- Description on the [difference between tools and workflows](https://docs.dockstore.org/en/stable/advanced-topics/tools-vs-workflows.html) 
- Confusing aspect of the API: Dockstore calls them "tools" in the UI and the doc, but the API for accessing those tools instead uses the word "containers" in the endpoint
- According to Denis Yuen: “if your group does end up sticking with manual registration let us know. Deprecating manual registration is still in the planning stages and not a near term priority. We could consider something like limit manual registration to administrators or power users, or remove/deprecate the UI portion only.“

Acceptance Criteria:
- Unity.py updated to allow programmatic management of hosted workflows in Dockstore
- Hosted workflow created can be extracted for running in SPS

**Comment by mcduffie** [comment]
Currently the Unity.py access to Dockstore API uses deprecated end points. Convert to use Dockstore Hosted Workflows.

**Comment by mliukis** [comment]
From team meetings:
    * Modify application_service in unity-py code to support hosted workflows using the Dockstore API #hosted API
    * Use tutorial notebook as example to get started with ([dockstore publish example notebook](https://github.com/unity-sds/sounder-sips-tutorial/blob/mcduffie/jupyter-notebooks/tutorials/dockstore_publish.ipynb))
    * Modify register() and unregister methods to use hosted workflows

**Comment by rtapella** [comment]
Should this be in the unity-py repo?

**Comment by rtapella** [comment]
Ideally we can use some "standardized" language in the unity.py API that isn't necessarily the same as the tools vs. containers vs. workflows that are used in Dockstore.

**Comment by rtapella** [comment]
is the application_descriptor.json thingy part of this work as well?
