### ISSUE TITLE
Verify Dockstore database can be restored after rebuild

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads-deployment#89]

**Comment by mliukis** [comment]
To restore DB from the snapshot in CloudFormation, use 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html:

**DBSnapshotIdentifier**

 The name or Amazon Resource Name (ARN) of the DB snapshot that's used to restore the DB instance. If you're restoring from a shared manual DB snapshot, you must specify the ARN of the snapshot.

 By specifying this property, you can create a DB instance from the specified DB snapshot. If the DBSnapshotIdentifier property is an empty string or the AWS::RDS::DBInstance declaration has no DBSnapshotIdentifier property, AWS CloudFormation creates a new database. If the property contains a value (other than an empty string), AWS CloudFormation creates a database from the specified snapshot. If a snapshot with the specified name doesn't exist, AWS CloudFormation can't create the database and it rolls back the stack.

**Comment by mliukis** [comment]
Having issues with re-deployment due to the [recent AWS security change](https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/ ) - can't create public S3 bucket for LB logs.

**Comment by mcduffie** [comment]
- Still dealing with issues related to S3 bucket policy changes
- Creating bucket manually
- Asking MCP to attach policy, waiting for ticket management review
- Once deployment done can test DB restore
- Terraform changes in place

**Comment by mliukis** [comment]
Was able to restore DB from manual snapshot for the brand new Dockstore deployment.

Just for the record, from Dockstore team:
```
Not specific to your issue, but more generally, we don't bring down the RDS between deployments, if we want to keep the same data between deployments.

If we do want to copy the DB to a new deployment, we do pg_dump, which saves the DB as a SQL file, then we run the SQL file against the new DB. It's a little more complex than that, depending on whether you want to to restore tokens or not; unfortunately those scripts are in our private repo.

We haven't tried restoring from RDS snapshots, although that's seemingly the more obvious route. It interacts weirdly with CloudFormation; it creates a new domain, so then you need to update the web service to reference the new domain, modify security groups, etc.
```

**Comment by mcduffie** [comment]
Please add some of this information into the README file for future reference. Specifically lay out some steps that one could go through for the restoring using pg_dump.
