### ISSUE TITLE
Bring test deployment setup in sync with dev deployment

### ISSUE THREAD

**Issue by mliukis** [unity-sds/unity-ads-deployment#96]
1. Create new GitHub App for `test` env:
   - Need to go through the same process as we did for the `dev` in order to be ready for the next time `test` needs to come down
2. Parameter Store variables in the `test` env:
    - There are a subset of the required parameters in the `test` env. All of the ones in `dev` should be added to test. Other than the GitHub App related ones which are already there, the others should be able to have matching values in both envs for now.
The names do need to reflect different environment (/DeploymentConfig/test/ instead of /DeploymentConfig/dev/)

**Comment by mliukis** [comment]
Current Dockstore in the test environment is deployed using Terraform/Cloudformation scripts. 
Remaining task:
* Automate selection of the private subnet based on the selected AZ for the ES

**Comment by mcduffie** [comment]
Closed by  4e053a225a48b5801c709394a923b85c2d68f8d8
